name: k6 Tests and Report Deployment
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  k6-run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Linter and Prettier
        run: |
          npm run lint
          npm run prettier

      - name: Create report directory
        run: mkdir -p report

      - name: Setup k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 tests
        uses: grafana/run-k6-action@v1
        continue-on-error: true
        env:
          BASE_URL: https://6820decb259dad2655adddab.mockapi.io/animals/animal
        with:
          path: |
            animals.test.ts

      - name: Upload k6 HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: k6-html-report
          path: report/
          retention-days: 30

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: report/
